apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  labels:
    app: room-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      name: room-booking
  template:
    metadata:
      labels:
        name: room-booking
    spec:
      containers:
        - name: room-booking
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
          {{- range $key, $value := .Values.envs }}
          - name: {{ $value.name }}
            value: {{ $value.value }}
          {{- end }}