apiVersion: v1
kind: Service
metadata:
  labels:
    app: room-booking
  name: room-booking
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: room-booking
  sessionAffinity: ClientIP
  type: {{ .Values.service.type }}
